version: "3"
services:
  server:
    build:
      context: ./server/cmap
      dockerfile: Dockerfile
    container_name: cmap_server
    ports:
      - 8080:8080
    networks:
      - network-tier
    restart: on-failure
    tty: true

  web:
    container_name: cmap_web
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    # ports:
    #   - 3000:3000
    volumes:
      - ./web:/web
      - build_folder:/web/dist
      - ./web/node_modules/:/web/node_modules
    tty: true

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - build_folder:/var/www/web
    depends_on:
      - web
      - server
    networks:
      - network-tier

networks:
  network-tier:
    driver: bridge

volumes:
  build_folder: null
